config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sche_app.urls')),
]

sche_app/urls.py
from django.urls import path

from . import views

app_name = 'sche_app'

urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    path('new_sche', views.CreateView.as_view(), name='new_sche'),
    path('edit_sche/<int:pk>', views.UpdateView.as_view(), name='edit_sche'),
    path('delete_sche/<int:pk>', views.DeleteView.as_view(), name='delete_sche'),
    path('new_task', views.CreateTaskView.as_view(), name='new_task'),
    # 仕事情報の編集のパスを通す
    path('edit_task/<int:pk>', views.UpdateTaskView.as_view(), name='edit_task'),
    # タスクの内容を編集するためのパスを通す
    path('delete_task/<int:pk>', views.DeleteTaskView.as_view(), name='delete_task'),

]

sche_app/models.py
from django.db import models
from django.urls.base import reverse 

# Create your models here.
class Schedule(models.Model):
    time = models.DateTimeField()
    task = models.ForeignKey(
        'Task',
        on_delete = models.CASCADE,
    )
    amount = models.IntegerField()
    worker = models.CharField(max_length=150)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.task.task

    def get_absolute_url(self):
        return reverse ('sche_app:index')

class Task(models.Model):
    task = models.CharField(max_length=150)
    unit = models.CharField(max_length=150)
    point = models.IntegerField()

    def __str__(self):
        return self.task

sche_app/forms.py
from django import forms
from django.forms import fields
from . models import Schedule, Task

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'
        widgets = {
            'time': forms.SelectDateWidget
        }

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

sche_app/views.py
from sche_app.forms import ScheduleForm, TaskForm
from django.shortcuts import render
from django.views import generic
from .models import Schedule, Task
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    return render(request,'app/index.html')

class IndexView(generic.ListView):
    model = Schedule
    template_name = 'app/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(generic.ListView, self).get_context_data(**kwargs)
        context.update({
            'object_list2': Task.objects.all()
        })
        return context

    def get_queryset(self):
        return Schedule.objects.all().order_by('-time')


class CreateView(generic.CreateView):
    form_class = ScheduleForm
    template_name = 'app/new_sche.html'

class UpdateView(generic.UpdateView):
    model = Schedule
    form_class = ScheduleForm
    template_name = 'app/edit_sche.html'

class DeleteView(generic.edit.DeleteView):
    model = Schedule
    success_url = reverse_lazy('sche_app:index')
    template_name = 'app/delete.html'

class CreateTaskView(generic.CreateView):
    model = Task
    success_url = reverse_lazy('sche_app:index')
    fields = ['task','unit','point']
    template_name = 'app/new_task.html'

class UpdateTaskView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'app/edit_task.html'
    success_url = reverse_lazy('sche_app:index')
    # fields = ['task','unit','point']

class DeleteTaskView(generic.DeleteView):
    model = Task
    # form_class = TaskForm
    template_name = 'app/delete_task.html'
    success_url = reverse_lazy('sche_app:index')

sche_app/templates/app/base.html
<!DOCTYPE html>


<html>


<head>
    
    <title>すけじゅる</title>

</head>

<body>
    <div class="container"> 
        {% block content %} {% endblock %}
    </div>
</body>


</html>

sche_app/templates/app/delete_sche.html
{% extends 'app/base.html' %}
{% block content %}

<h1>スケジュールを消しちゃうよ</h1>
<p>{{ object.time | date:'Y/m/d' }}の{{ object.task }}をほんとに消すと？</p>
<form action="" method='post'>
    {% csrf_token %}
    <button type='submit' class='submit delete'>削除する</button>
</form>

<div>
    <p><a href="Javascript:history.back()">&lt; 戻る</a></p>
</div>

{% endblock %}

sche_app/templates/app/delete_task.html
{% extends 'app/base.html' %}
{% block content %}

<h1>おしごとのじょうほーを消しちゃうよ</h1>
<p>{{ object.task }}をほんとに消すと？</p>
<p>注）{{ object.task }}が登録されているスケジュールも同時に削除されます。</p>
<form action="" method='post'>
    {% csrf_token %}
    <button type='submit' class='submit delete'>削除する</button>
</form>

<div>
    <p><a href="Javascript:history.back()">&lt; 戻る</a></p>
</div>

{% endblock %}

sche_app/templates/app/edit_sche.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'sche_app:index' %}">ホームに戻る</a>
</div>

<h1>すけじゅるのへんしゅー</h1>

<form action="{% url 'sche_app:edit_sche' object.id %}" method="POST">

    {% csrf_token %}

    <table>
        <tr>
            <th>日時</th>
            <td>{{ form.time }}</td>
        </tr>

        <tr>
            <th>内容</th>
            <td>{{ form.task }}</td>
        </tr>

        <tr>
            <th>仕事量</th>
            <td>{{ form.amount }}</td>
        </tr>

        <tr>
            <th>作業者</th>
            <td>{{ form.worker }}</td>
        </tr>

    </table>

    <button type="submit" class="btn">保存</button>
    
</form>

{% endblock %}

sche_app/templates/app/edit_task.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'sche_app:index' %}">ホームに戻る</a>
</div>

<h1>おしごとないようのへんしゅー</h1>

<form action="{% url 'sche_app:edit_task' object.id %}" method="POST">

    {% csrf_token %}

    <table>
        <tr>
            <th>内容</th>
            <td>{{ form.task }}</td>
        </tr>

        <tr>
            <th>単位</th>
            <td>{{ form.unit }}</td>
        </tr>

        <tr>
            <th>ポイント</th>
            <td>{{ form.point }}</td>
        </tr>

    </table>

    <button type="submit" class="btn">保存</button>
    
</form>

{% endblock %}

sche_app/templates/app/index.html
{% extends './base.html' %}


{% block content %} 

<h1>すけじゅーる</h1>
    <table border="1">
        <tr>
            <th>日時</th><th>内容</th><th>仕事量</th><th>作業中</th><th>編集</th><th>削除</th>
        </tr>

{% for schedule in object_list %}
    <tr>
        <td>{{ schedule.time| date:'Y/m/d' }}</td>
        <td>{{ schedule.task }}</td>
        <td>{{ schedule.amount }}  {{ schedule.task.unit }}</td>
        <td>{{ schedule.worker }}</td>
        <td><a href="{% url 'sche_app:edit_sche' schedule.id %}">編集</a></td>
        <td><a href="{% url 'sche_app:delete_sche' schedule.id %}">削除</a></td>

    </tr>
{% endfor %}
    </table>

    <a class="btn btn-primary" href="{% url 'sche_app:new_sche' %}">スケジュール作成</a>

<h2>仕事情報</h2>

<table border="1">
    <tr>
        <th>仕事内容</th>
        <th>単価</th>
        <th>ポイント</th>
    </tr>
    {% for task in object_list2 %}
    <tr>
        <td>{{ task.task }}</td>
        <td>{{ task.unit }}</td>
        <td>{{ task.point }}</td>
        <td><a class="btn btn-primary" href="{% url 'sche_app:edit_task' task.id %}">編集</a></td>
        <td><a class="btn btn-primary" href="{% url 'sche_app:delete_task' task.id %}">削除</a></td>
    </tr>
    {% endfor %}
</table>

    <a class="btn btn-primary" href="{% url 'sche_app:new_task' %}">あたらしいおしごとーー</a>


{% endblock %}

sche_app/templates/app/new_sche.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'sche_app:index' %}">ホームに戻る</a>
</div>

<h1>スケジュール</h1>

<form action="{% url 'sche_app:new_sche' %}" method="POST">

    {% csrf_token %}

    <table>
        <tr>
            <th>日時</th>
            <td>{{ form.time }}</td>
        </tr>

        <tr>
            <th>内容</th>
            <td>{{ form.task }}</td>
        </tr>

        <tr>
            <th>仕事量</th>
            <td>{{ form.amount }}</td>
        </tr>

        <tr>
            <th>作業者</th>
            <td>{{ form.worker }}</td>
        </tr>

    </table>

    <button type="submit" class="btn">保存</button>
    
</form>

{% endblock %}

sche_app/templates/app/new_task.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'sche_app:index' %}">ホームに戻る</a>
</div>

<h1>おしごとのあたらしいのーー</h1>

<form action="{% url 'sche_app:new_task' %}" method="POST">

    {% csrf_token %}

    <table>
        <tr>
            <th>仕事内容</th>
            <td>{{ form.task }}</td>
        </tr>

        <tr>
            <th>単位</th>
            <td>{{ form.unit }}</td>
        </tr>

        <tr>
            <th>ポイント</th>
            <td>{{ form.point }}</td>
        </tr>

    </table>

    <button type="submit" class="btn">保存</button>
    
</form>

{% endblock %}